"""modified event

Revision ID: 3bdbf3cbc509
Revises: 70d5f74d966d
Create Date: 2025-05-29 13:44:35.114161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdbf3cbc509'
down_revision: Union[str, None] = '70d5f74d966d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
