"""cascade

Revision ID: 9229f8fb968b
Revises: 34cdfdde6515
Create Date: 2025-05-29 15:23:50.531451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9229f8fb968b'
down_revision: Union[str, None] = '34cdfdde6515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_attendees_event_id_fkey'), 'event_attendees', type_='foreignkey')
    op.drop_constraint(op.f('event_attendees_user_id_fkey'), 'event_attendees', type_='foreignkey')
    op.create_foreign_key(None, 'event_attendees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_attendees', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_attendees', type_='foreignkey')
    op.drop_constraint(None, 'event_attendees', type_='foreignkey')
    op.create_foreign_key(op.f('event_attendees_user_id_fkey'), 'event_attendees', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('event_attendees_event_id_fkey'), 'event_attendees', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
