"""modified event added event attendes

Revision ID: aa7b1b52df82
Revises: 3bdbf3cbc509
Create Date: 2025-05-29 13:54:08.491112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7b1b52df82'
down_revision: Union[str, None] = '3bdbf3cbc509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendees',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_role', sa.Enum('ORGANIZER', 'SPEAKER', 'ATTENDEE', name='eventroleenum'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.drop_constraint(op.f('events_creator_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('events_creator_id_fkey'), 'events', 'users', ['creator_id'], ['id'])
    op.drop_table('event_attendees')
    # ### end Alembic commands ###
