"""modified relation events

Revision ID: f0ce729ea80e
Revises: aa7b1b52df82
Create Date: 2025-05-29 14:07:45.201864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ce729ea80e'
down_revision: Union[str, None] = 'aa7b1b52df82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attendees', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_attendees', 'id')
    # ### end Alembic commands ###
